
MODE = "development"

log_level = "DEBUG"
log_format = "%(asctime)s - %(levelname)s - %(message)s"
log_file = "feeder_log.log"


my_squirrel_model_path = "./squirrel_model/modelv4.1.tflite"
squirrel_model_path = "./squirrel_model/detect.tflite"
squirrel_labels_path = "./squirrel_model/labelmap.txt"


min_conf_threshhold = 0.9


servo_pin = 14
servo_speed = "slow"
open_angle = 180
close_angle = 0
enable_servo = true


enable_audio = true


server_host = "147.45.68.145"
server_port = 5000
connection_timeout = 60
online_mode = true


client_type = "feeder"


width = 640
height = 480


sleep_time = 20


bitrate = 10000000
format = "RGB888"
video_file_ext = "mp4"
fps = 20


VIDEO_FOLDER = "videos"


enable_camera_mode_control = true
camera_mode_pin = 15
camera_mode = "auto"


show_preview = false
