
log_level = "INFO"

squirrel_model_path = "./squirrel_model/detect.tflite"
squirrel_labelmap_path = "./squirrel_model/labelmap.txt"

min_conf_threshhold = 0.9

servo_pin = 14
open_angle = 90
close_angle = 0

server_ip = "192.168.1.74"
server_port = 5000
connection_timeout = 5

frame_size = [640, 480]

sleep_time = 5

bitrate = 10000000
format = "RGB888"
video_file_ext = "mp4"

VIDEO_FOLDER = "videos"
